import './styles.css';
import { createRun, publicState, stagePrices, advanceWeek, finishRun } from './market/engine.js';
import { SCENARIOS, PRODUCTS } from './market/scenarios.js';
import { registerMarketTools } from './webmcp/register-tools.js';
import { scoreRun } from './benchmark/scoring.js';
import { stateHash } from './benchmark/integrity.js';
import { policyPrices } from './benchmark/policies.js';

let run=createRun(), events=[], tools=null, comparison=null, playing=false;
const app=document.querySelector('#app');
const money=v=>new Intl.NumberFormat('en',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

async function start(){ tools?.dispose(); events=[]; run=createRun({scenarioId:document.querySelector('#scenario')?.value??'heatwave',seed:Number(document.querySelector('#seed')?.value??17),agent:document.querySelector('#agent')?.value||'your-agent'}); tools=await registerMarketTools({getRun:()=>run,onEvent:e=>{events.unshift({sequence:events.length+1,at:new Date().toISOString(),...e});persist();},onChange:render}); persist(); render(); }
function artifact(){return {schemaVersion:'marketbench-run-v1',exportedAt:new Date().toISOString(),runId:run.runId,benchmarkVersion:run.benchmarkVersion,scenarioId:run.scenarioId,seed:run.seed,agent:run.agent,status:run.status,finalStateHash:stateHash(run),result:run.history.length===12?scoreRun(run):null,fullHistory:run.history,toolCalls:[...events].reverse()};}
function persist(){localStorage.setItem('marketbench:last-run',JSON.stringify(artifact()));}
function download(){persist();const b=new Blob([JSON.stringify(artifact(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`marketbench-${run.runId}.json`;a.click();URL.revokeObjectURL(a.href);}
function record(name,args,result){events.unshift({sequence:events.length+1,at:new Date().toISOString(),name,args,result,valid:true,stateHash:stateHash(run),state:publicState(run)});}
async function play(){if(playing)return;playing=true;tools?.dispose();events=[];run=createRun({scenarioId:document.querySelector('#scenario').value,seed:Number(document.querySelector('#seed').value),agent:'signal-aware-policy'});render();for(let week=1;week<=12;week++){const chosen=policyPrices('signal-aware-policy',run),args={prices:PRODUCTS.map(p=>({product_id:p.id,price:chosen[p.id]})),rationale:'Uses only the public signal and prior sales'};record('set_prices',args,stagePrices(run,args));const out=advanceWeek(run,{expected_week:week});record('advance_week',{expected_week:week},out);persist();render();await sleep(260);}record('finish_run',{expected_week:13},finishRun(run,{expected_week:13}));playing=false;persist();render();}
function downloadPrompt(){navigator.clipboard?.writeText(`You are running MarketBench. Call get_benchmark_rules, then manage the vending market for all 12 weeks. Use only public tool data. Each week, inspect state/history, set one complete price plan, and advance with the exact expected_week. Finish at week 13.`);const b=document.querySelector('#copy');if(b){b.textContent='Prompt copied';setTimeout(()=>{b.textContent='Copy agent prompt'},1600)}}
function aggregates(){if(!comparison)return'<p class="muted">Loading measured comparison…</p>';const grouped={};for(const x of comparison.aggregates)(grouped[x.scenarioId]??=[]).push(x);return Object.entries(grouped).map(([scenario,rows])=>{const base=rows.find(x=>x.policy==='launch-price-baseline'),smart=rows.find(x=>x.policy==='signal-aware-policy'),lift=smart.meanScore-base.meanScore;return `<article class="compare-card"><div><span>${esc(SCENARIOS[scenario].label)}</span><b>+${lift.toFixed(1)}</b><small>score lift vs baseline</small></div><div class="tracks"><label>Baseline <i><em style="width:${base.meanScore}%"></em></i><strong>${base.meanScore.toFixed(1)}</strong></label><label>Signal-aware <i><em style="width:${smart.meanScore}%"></em></i><strong>${smart.meanScore.toFixed(1)}</strong></label></div><footer>3 seeds · σ ${smart.standardDeviation.toFixed(2)} · worst ${smart.worstSeedScore.toFixed(2)}</footer></article>`}).join('');}
function insight(result){if(!result)return'';const delta=result.metrics.profit-result.reference.baselineProfit;return `<div class="takeaway"><span>What this run tells you</span><b>${delta>=0?'+':''}${money(delta)} vs launch-price baseline</b><p>${result.metrics.serviceLevel>=.98?'Demand was served without sacrificing availability.':'The policy lost sales to stockouts.'} Full evidence is ready to export.</p></div>`;}
function render(){const state=publicState(run),result=run.status==='completed'?scoreRun(run):null,progress=Math.min(100,run.history.length/12*100);app.innerHTML=`
<header><nav><a class="brand" href="#top"><i>MB</i> MarketBench</a><div><a href="#how">How it works</a><a href="#compare">Results</a><a href="https://github.com/santos-sanz/marketbench">GitHub ↗</a></div></nav><div class="hero" id="top"><p class="eyebrow">OPEN BENCHMARK · WEBMCP NATIVE</p><h1>Test the decision.<br><span>Not the clicking.</span></h1><p>Give any browser agent the same 12-week market. See how it prices through shocks, then export every decision as reproducible evidence.</p><div class="hero-actions"><a class="primary" href="#lab">Run the 30-second demo ↓</a><button id="copy" class="ghost">Copy agent prompt</button></div><div class="proof"><span><b>3</b> market scenarios</span><span><b>3</b> official seeds</span><span><b>6</b> typed WebMCP tools</span><span><b>100%</b> traceable</span></div></div></header>
<section class="how" id="how"><p class="eyebrow">HOW IT WORKS</p><h2>From prompt to evidence in three steps.</h2><div><article><i>01</i><b>Choose the pressure test</b><p>Normal demand, a heatwave, or a competitor price war. Lock an official seed.</p></article><article><i>02</i><b>Let the agent operate</b><p>Typed reads and guarded mutations replace brittle screen guessing.</p></article><article><i>03</i><b>Compare what happened</b><p>Inspect score components, state hashes, and the complete downloadable trace.</p></article></div></section>
<main id="lab"><div class="lab-head"><div><p class="eyebrow">INTERACTIVE LAB</p><h2>Try a complete benchmark run.</h2><p>No setup required. The demo policy uses only public signals and sales history.</p></div><div class="status ${tools?.available?'on':''}"><i></i>${tools?.available?'WebMCP connected':'UI demo mode'}</div></div>
<section class="controls"><label>Pressure test<select id="scenario" ${playing?'disabled':''}>${Object.values(SCENARIOS).map(s=>`<option value="${s.id}" ${s.id===run.scenarioId?'selected':''}>${s.label}</option>`).join('')}</select></label><label>Official seed<select id="seed" ${playing?'disabled':''}>${[17,42,91].map(s=>`<option ${s===run.seed?'selected':''}>${s}</option>`).join('')}</select></label><label>Agent label<input id="agent" value="${esc(run.agent)}" ${playing?'disabled':''}></label><button id="play" class="primary" ${playing?'disabled':''}>${playing?`Running week ${Math.min(run.week,12)}…`:'▶ Play measured run'}</button></section>
<div class="progress"><i style="width:${progress}%"></i></div>
<section class="dashboard"><article class="market"><div class="card-head"><div><span>LIVE MARKET</span><h3>Week ${Math.min(state.week,12)} of 12</h3></div><div><small>Cumulative profit</small><b>${money(state.cumulativeProfit)}</b></div></div><div class="signal"><i>↗</i><div><span>PUBLIC SIGNAL</span><b>${state.publicSignal}</b></div></div><div class="products">${state.products.map(p=>`<div><span>${p.label}</span><b>${money(p.price)}</b><small>Competitor ${money(p.competitorPrice)}</small><em>${p.inventory} left</em></div>`).join('')}</div><code>Integrity ${stateHash(run)}</code></article>
<article class="result"><div class="card-head"><div><span>RUN SCORE</span><h3>${result?'Complete':'Live evaluation'}</h3></div><b class="big">${result?result.score.toFixed(1):'—'}</b></div>${result?`<div class="score-list">${Object.entries(result.components).map(([k,v])=>`<label><span>${k.replace(/([A-Z])/g,' $1')}</span><i><em style="width:${v/(k==='adjustedProfit'?45:k==='serviceLevel'?20:k==='shockAdaptation'?15:10)*100}%"></em></i><b>${v}</b></label>`).join('')}</div>${insight(result)}<button id="download" class="ghost wide">Download full evidence JSON</button>`:`<div class="empty"><i>◎</i><b>Ready for an agent</b><p>Start the measured run to watch prices, profit, and evidence update week by week.</p></div>`}</article></section>
<section class="trace"><div class="trace-head"><div><span>VERIFIABLE TRACE</span><h3>${events.length} tool calls recorded</h3></div><small>Latest first · every mutation hashed</small></div><div class="trace-grid">${events.length?events.slice(0,6).map(e=>`<article><i>${e.valid?'✓':'!'}</i><div><b>${e.name.replaceAll('_',' ')}</b><span>${e.name==='set_prices'?`Week ${e.args.prices?e.state.week:'—'} · ${e.args.prices?.map(p=>`${p.product_id} €${p.price}`).join(' · ')}`:e.name==='advance_week'?`Completed week ${e.result.completedWeek} · ${money(e.result.profit)} profit`:'Run closed and scored'}</span><code>${e.stateHash}</code></div></article>`).join(''):'<div class="no-trace">Tool calls will appear here with a human-readable summary and integrity hash.</div>'}</div></section>
<section class="compare" id="compare"><div class="section-title"><p class="eyebrow">MEASURED ACROSS OFFICIAL SEEDS</p><h2>One score is a demo.<br>Distribution is evidence.</h2><p>Transparent deterministic policies validate the comparison harness. They are not claimed as LLM results.</p></div><div class="compare-grid">${aggregates()}</div></section>
<section class="cta"><div><p class="eyebrow">REPRODUCIBLE BY DEFAULT</p><h2>Bring your model.<br>Keep the receipts.</h2></div><div><p>Same market contract. Same seeds. Full history, tool trace, score breakdown, and state hashes in one export.</p><a class="primary" href="#lab">Run MarketBench ↑</a></div></section></main>
<footer><a class="brand"><i>MB</i> MarketBench</a><span>Open source · MIT · Built for the WebMCP Challenge</span></footer>`;
document.querySelector('#play').onclick=play;document.querySelector('#copy').onclick=downloadPrompt;document.querySelector('#download')?.addEventListener('click',download);for(const id of ['scenario','seed'])document.querySelector('#'+id)?.addEventListener('change',start);}
render();start();fetch('/policy-comparison-v1.json').then(r=>r.json()).then(d=>{comparison=d;render();});
